<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs0l3RcjmzNBZzUyJTqVi'."\n".'9hsoZ5E2CtR4Ef6/ayqnx9qlDjQ4DKdc8NaWmtIdRAVoHt4WsTcPb2dYf6Px5xaH'."\n".'HKqzVRodlf5URi6zTJrJchiLR9gneTt++PJFwr9v+xcUgMKbwo1WUHjKPLF9YKLR'."\n".'FQ77fRFFeIXyEv+Kk9VNsO/IcsDDg/uG6Bo+/emdRJeYaD+nQVV/2X0CnlWpfTB0'."\n".'PoqF9qpY14flQyySBYioQbspjMEWfp4RXlRmEppbVfWqZbuS39mXTcVHRRPz4nC5'."\n".'37vA07RZSpcAEC1XcuPX5s1LssXxadQkMpf8QTJok7i1Kx8OfP6uAtfRq+H6CnIE'."\n".'4wIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
