<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.grid.definition.factory.whcallbackrequest_grid_definition_factory' shared service.

$this->services['webhelpers.whcallback.grid.definition.factory.whcallbackrequest_grid_definition_factory'] = $instance = new \WebHelpers\WHCallback\Grid\Definition\Factory\WHCallbackRequestDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
