<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.domain.setting.command_handler.edit_setting' shared service.

return $this->services['webhelpers.whcallback.domain.setting.command_handler.edit_setting'] = new \WebHelpers\WHCallback\Domain\Setting\CommandHandler\EditSettingHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), 'WHCALLBACK_HOURS');
