<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.domain.setting.query_handler.get_setting_for_editing_handler' shared service.

return $this->services['webhelpers.whcallback.domain.setting.query_handler.get_setting_for_editing_handler'] = new \WebHelpers\WHCallback\Domain\Setting\QueryHandler\GetSettingForEditingHandler(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())), 'WHCALLBACK_HOURS');
