<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxJZhHo\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxJZhHo/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVxJZhHo.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVxJZhHo\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVxJZhHo\appAppKernelProdContainer([
    'container.build_hash' => 'VxJZhHo',
    'container.build_id' => '98f3aad5',
    'container.build_time' => 1707839568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxJZhHo');
