<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI1hy0Jm\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI1hy0Jm/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI1hy0Jm.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI1hy0Jm\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerI1hy0Jm\appAppKernelDevDebugContainer([
    'container.build_hash' => 'I1hy0Jm',
    'container.build_id' => '4597fb1b',
    'container.build_time' => 1708692215,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI1hy0Jm');
