<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEE8RvHq\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEE8RvHq/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEE8RvHq.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEE8RvHq\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerEE8RvHq\appAppKernelProdContainer([
    'container.build_hash' => 'EE8RvHq',
    'container.build_id' => '716706ab',
    'container.build_time' => 1707841013,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEE8RvHq');
