<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.form.identifiable_object.data_provider.setting_form_data_provider' shared service.

return $this->services['webhelpers.whcallback.form.identifiable_object.data_provider.setting_form_data_provider'] = new \WebHelpers\WHCallback\Form\Setting\DataProvider\SettingFormDataProvider(($this->services['prestashop.core.query_bus'] ?? $this->load('getPrestashop_Core_QueryBusService.php')));
