<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.form.identifiable_object.builder.setting_form_builder' shared service.

return $this->services['webhelpers.whcallback.form.identifiable_object.builder.setting_form_builder'] = ($this->services['prestashop.core.form.builder.form_builder_factory'] ?? $this->load('getPrestashop_Core_Form_Builder_FormBuilderFactoryService.php'))->create('WebHelpers\\WHCallback\\Form\\Type\\SettingType', ($this->services['webhelpers.whcallback.form.identifiable_object.data_provider.setting_form_data_provider'] ?? $this->load('getWebhelpers_Whcallback_Form_IdentifiableObject_DataProvider_SettingFormDataProviderService.php')));
