<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.form.identifiable_object.handler.setting_form_handler' shared service.

return $this->services['webhelpers.whcallback.form.identifiable_object.handler.setting_form_handler'] = ($this->services['prestashop.core.form.identifiable_object.handler.form_handler_factory'] ?? $this->load('getPrestashop_Core_Form_IdentifiableObject_Handler_FormHandlerFactoryService.php'))->create(($this->services['webhelpers.whcallback.form.identifiable_object.data_handler.setting_form_data_handler'] ?? $this->load('getWebhelpers_Whcallback_Form_IdentifiableObject_DataHandler_SettingFormDataHandlerService.php')));
