<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcategoryfields.domain.hcategoryfieldsextension.command_handler.add_extension' shared service.

return $this->services['webhelpers.whcategoryfields.domain.hcategoryfieldsextension.command_handler.add_extension'] = new \WebHelpers\WHCategoryFields\Domain\WHCategoryFieldsExtension\CommandHandler\AddExtensionHandler(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['webhelpers.whcategoryfields.repository.whcategoryfieldsextension_repository'] ?? $this->load('getWebhelpers_Whcategoryfields_Repository_WhcategoryfieldsextensionRepositoryService.php')), ($this->services['prestashop.core.admin.lang.repository'] ?? $this->getPrestashop_Core_Admin_Lang_RepositoryService()));
