<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.domain.whcallbackrequest.command_handler.delete_request' shared service.

return $this->services['webhelpers.whcallback.domain.whcallbackrequest.command_handler.delete_request'] = new \WebHelpers\WHCallback\Domain\WHCallbackRequest\CommandHandler\DeleteWHCallbackRequestHandler(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['webhelpers.whcallback.repository.whcallbackrequest_repository'] ?? $this->load('getWebhelpers_Whcallback_Repository_WhcallbackrequestRepositoryService.php')));
