<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcallback.form.identifiable_object.data_handler.setting_form_data_handler' shared service.

return $this->services['webhelpers.whcallback.form.identifiable_object.data_handler.setting_form_data_handler'] = new \WebHelpers\WHCallback\Form\Setting\DataHandler\SettingFormDataHandler(($this->services['prestashop.core.command_bus'] ?? $this->load('getPrestashop_Core_CommandBusService.php')));
