<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'webhelpers.whcategoryfields.domain.hcategoryfieldsextension.command_handler.delete_extension_file' shared service.

return $this->services['webhelpers.whcategoryfields.domain.hcategoryfieldsextension.command_handler.delete_extension_file'] = new \WebHelpers\WHCategoryFields\Domain\WHCategoryFieldsExtension\CommandHandler\DeleteExtensionFileHandler(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['webhelpers.whcategoryfields.repository.whcategoryfieldsextension_repository'] ?? $this->load('getWebhelpers_Whcategoryfields_Repository_WhcategoryfieldsextensionRepositoryService.php')));
